### PR TITLE
Try mounting again if it didn't mount the first time

### PR DESCRIPTION
**Pull request by karx1**
This is for drives like mine, where the persistent partition is not detected immediately at boot.

### CODE REVIEW

**Comment by Admicos** [comment]
Wouldn't a better approach be to continuously check for the disk's
existence, and time out after a certain amount of time?

psuedocode:
```bash

for TRY in 3 times
    if exists /dev/disk/by-label/SNAKEUSER; do
        echo "Persistent storage found"
        mount /dev/disk/by-label/SNAKEUSER /snakeuser
        break
    else
        echo "Waiting for persistent storage (try $TRY)"
        sleep 1
    end
end

# ...continue boot

```

But that would add unneccesary boot delay to people who don't want
persistent storage...

**Comment by karx1** [comment]
Yeah, you're right. We could do it in a separate thread on the python side,
but we have no way to notify the user that their partition has been found.
Also, it wastes a lot of processing power for users who just want a live
environment.

**Comment by karx1** [comment]
@Admicos I took what you said and implemented it, and it works really well. It doesn't even add that much delay to boot. Tested with persistent and non-persistent modes.

**Comment by Admicos** [comment]
I don't think you need anything in the Python side of things. You could just move that file up to the init script. It would be cleaner IMO.

**Comment by karx1** [comment]
Yeah. I'll do some more testing tomorrow. Something I noticed is that the unit script usually doesn't pick up the drive, because it's not a regular file? I'll try and find a fix for that, and then I can just remove the python part.

**Comment by karx1** [comment]
Ok, did some googling and turns out it's an easy fix. Still haven't tested it, because it's 10 PM here, but it should work. Will remove the code on the python side tomorrow.

**Comment by karx1** [comment]
Did some testing and modifications, works now. Also removed the mount on the Python side. This PR is ready to be merged.

**Comment by karx1** [comment]
Hello @joshiemoore, just as a reminder, this PR is ready for review.

**Comment by karx1** [comment]
Bump @joshiemoore

**Pull request merged**
