### PR TITLE
Add analog clock app

### PR DESCRIPTION
**Pull request by mdoege**
Just an analog clock based on my AmigaClock code, but with a modified dial design and caching of the empty dial image for better performance. The pygame_gui-related stuff is patterned after dance.py.

### CODE REVIEW

**Comment by Abdur-rahmaanJ** [comment]
Was thinking: could you not merge it with the existing  clock below the digital display?

**Comment by mdoege** [comment]
Yes, good idea. Done.

**Comment by Abdur-rahmaanJ** [comment]
The result is the same though you did it the other way round. Now you can see the readme in the original clock + you can rename it from a clock to clock

**Comment by mdoege** [comment]
Don't you want to keep the digital clock in Snakeware too? It's small and space-saving, some people might prefer that to big analog clock.

**Comment by joshiemoore** [comment]
I think the digital clock should be the digital clock and the analog clock should be the analog clock. I don't see a reason to merge the two, they're two different things

**Comment by mdoege** [comment]
The project creator has spoken, so I have reverted it to the original version.

**Comment by joshiemoore** [comment]
This looks really amazing, as one more thing could you just set `resizable` to `False` for the window? The clock doesn't scale when the window is resized, which is fine but it looks strange when the window is resized smaller the clock surface

**Comment by Abdur-rahmaanJ** [comment]
@joshiemoore like if it dies not clutter then fine ^^_

**Comment by mdoege** [comment]
Originally I wanted the clock to scale, that is why that flag was set. But I could not figure out how this works in pygame_gui. Maybe it can be added later...

**Comment by joshiemoore** [comment]
Thanks again, this is super cool, feel free to open another PR if you end up making it scale with a resizing window!

**Pull request merged**
