### PR TITLE
Added two new games into the games folder

### PR DESCRIPTION
**Pull request by diayush**
I added two new games into the games folder. Note that, I didn't changed any code to make those folders show up in menu though. I guess you can do that yourself. So, that's it.

### CODE REVIEW

**Comment by joshiemoore** [comment]
Hi, thanks for sending this! There are a few things that need to be changed before I merge this, I can make some of the changes if you give me write access on your fork.

* I would prefer you submit your "Crappy Bird" game directly instead of adding a submodule.
* Your games do not have an `__init__.py` with a `load()` function (see the other apps for examples).
* Your games are calling `pygame.init()` and drawing to `pygame.display`, but this is not how snakeware apps are going to work. The games will need to be tweaked so that they create a pygame_gui UIWindow and draw directly to that instead of drawing to `pygame.display`. The pong game is a good example of how this can be structured.

Thank you!

**Comment by diayush** [comment]
_I can make some of the changes if you give me write access on your fork_

Actually, I'm not good at git. I don't know how to give you permission for that. Can you make a fork of that repo and do a pull request? I'll merge it, then you could do the same.

**Comment by joshiemoore** [comment]
Hi, I think it would be easiest if I just copied the code and incorporated it manually. Would that be okay with you? I'll add a README.txt in the directory for each game crediting you and displaying a link to your GitHub profile.

**Comment by diayush** [comment]
Well, it would it have been better the other way. If you can do that, it'll be much better. But if you're having trouble doing that, I guess you do it your way, if you want.

**Comment by dargonforce** [comment]
@diayush I think you can give @joshiemoore access by going to https://github.com/diayush/snakeware/settings/access and inviting joshiemoore as a collaborator.  You can then give him the permissions he needs.

Hope that helped :)

**Comment by diayush** [comment]
@dargonforce Thanks, mate. I gave joshiemoore access as a collaborator, I think now he can make changes to my fork and do the merge properly.

**Pull request closed without merging**
