### PR TITLE
Underlying system changes

### PR DESCRIPTION
**Pull request by Admicos**
Partly replaces #30 

<details><summary>View Change List</summary>
<p>

- Chroot-based build environment is removed (https://github.com/joshiemoore/snakeware/pull/30#issuecomment-639876668)
    - Unusual configurations can use the `contrib/nix/default.nix` file with the [Nix package manager]'s `nix-shell` feature. (3748658)
        - Completely optional

- Commits are organized in a better way
    - Everything after commit 4d65d60 should be easy to add or remove without affecting more than necessary.

- Uses Buildroot's external configuration support (7b94a48)
    - No more copying configuration files around before build, all done automatically

- Build hybrid ISOs instead of IMG files (48ac4ae)
    - Easier to write to USB/CD or boot in a virtual environment
    - To make this happen, Grub has been replaced with ISOLinux

- Buildroot packages for pyttsx3 and pygame_gui (598542e)

- Enable ccache by default (30fa88a)
    - Cache compiler outputs for faster clean builds
    - Maximum cache size set to 20 GB

- Optimize target packages with -O3 (52db9ca)
    - Includes the kernel, which _should_ work, but more testing can be nice

- Optimize Python (980808a)
    - Applies PGO and LTO to the built Python binary.
    - **Takes a long time to build**, so you might want to disable it when doing development.
        - Buildroot menuconfig: `External configuration -> Enable Optimizations for Python`

- Add `configure.sh` (484d228)
    - For easier editing of various component configurations
        - Also optional

- Try to slim down Busybox (1f7b04f) & Buildroot (c3e6a6f, 8567878)
    - I've only done very little testing with these. Might break some stuff, let me know if it does.

- Enable module autoload on boot (8c4dcf4)

- Enable GPU modules (8c4dcf4) and their firmware (cf9bad1)
    - GRUB set up the framebuffer before, but we use ISOLinux now, so we have to do this manually

- Add QEMU script (fad2ceb)
    - Just an example

[Nix package manager]: https://nixos.org/download.html

</p>
</details>

---

I am aware this PR might be too big, and contain changes that might be unnecessary. If so, please let me know and I'll remove the requested changes.

### CODE REVIEW

**Comment by Admicos** [comment]
Tested and working on my end, should be good to merge

**Comment by joshiemoore** [comment]
Hi, the whole process worked great, except for the last step where it's trying to build `host-cdrkit` to generate the ISO, I'm getting a bunch of linker errors:

```
/usr/bin/ld: CMakeFiles/genisoimage.dir/apple.o:(.bss+0x8): multiple definition of `outfile'; CMakeFiles/genisoimage.dir/genisoimage.o:(.bss+0x4d8): first defined here
/usr/bin/ld: CMakeFiles/genisoimage.dir/boot.o:(.bss+0x0): multiple definition of `outfile'; CMakeFiles/genisoimage.dir/genisoimage.o:(.bss+0x4d8): first defined here
/usr/bin/ld: CMakeFiles/genisoimage.dir/desktop.o:(.bss+0x0): multiple definition of `outfile'; CMakeFiles/genisoimage.dir/genisoimage.o:(.bss+0x4d8): first defined here

...

/usr/bin/ld: CMakeFiles/genisoimage.dir/rsync.o:(.bss+0x0): multiple definition of `outfile'; CMakeFiles/genisoimage.dir/genisoimage.o:(.bss+0x4d8): first defined here
/usr/bin/ld: CMakeFiles/genisoimage.dir/boot-mipsel.o:(.bss+0x0): multiple definition of `outfile'; CMakeFiles/genisoimage.dir/genisoimage.o:(.bss+0x4d8): first defined here
/usr/bin/ld: CMakeFiles/genisoimage.dir/checksum.o:(.bss+0x0): multiple definition of `outfile'; CMakeFiles/genisoimage.dir/genisoimage.o:(.bss+0x4d8): first defined here
```

I redacted many errors for brevity. Do you have any ideas what would be causing this?

Also, I believe the usage message for `configure.sh` is backwards. It says `./configure.sh <platform> <component>` but what is actually expects is `<component> <platform>`.

This is really great though, thank you for your help!!

**Comment by Admicos** [comment]
On Wed, 10 Jun 2020 16:35:18 -0700
Josh Moore <notifications@github.com> wrote:

> Hi, the whole process worked great, except for the last step where
> it's trying to build `host-cdrkit` to generate the ISO, I'm getting a
> bunch of linker errors:
> [snip]
> I redacted many errors for brevity. Do you have any ideas what would
> be causing this?

Seems to be a GCC 10 issue, maybe?

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=957074

> Also, I believe the usage message for `configure.sh` is backwards. It
> says `./configure.sh <platform> <component>` but what is actually
> expects is `<component> <platform>`.

Sorry, I guess I forgot to switch those around :p

**Comment by joshiemoore** [comment]
I downgraded to GCC 9.3 and this is really superior! isolinux boots way faster than GRUB, and only a 70MB image! Really really fantastic, thank you so much for this. These changes you made are going to help us so much.

**Pull request merged**
