### PR TITLE
Combined ramproc and cpuproc to sysmon (system monitor)

### PR DESCRIPTION
**Pull request by mochidaz**
Combined them so that we won't have to open two windows to see both ram and cpu usages. Also created the usage monitor in numbers

### CODE REVIEW

**Comment by callmepavo** [comment]
yeah this is sensible

**Comment by mochidaz** [comment]
Should i change the ram bar color to another color? It looks dull if both of them are blue

**Comment by callmepavo** [comment]
> Should i change the ram bar color to another color? It looks dull if both of them are blue

Yeah changing the colours would be good

**Comment by mochidaz** [comment]
aight gonna push the changes after this got merged together with https://github.com/mochidaz/snakeware/commit/514e38b41eaad5ef949f5a34e5169dd5d1ddf132

**Pull request merged**
