### PR TITLE
Added modulo operator to snakecalc

### PR DESCRIPTION
**Pull request by mochidaz**

### CODE REVIEW

**Comment by mochidaz** [comment]
The latest commit was just a deletion of tkinter text editor i forgot to delete. Here's the actual one: https://github.com/joshiemoore/snakeware/pull/70/commits/01a73fb4fbc956e534ec7e9a0f34f63cb3f64f33

**Comment by joshiemoore** [comment]
Hi, I like the mod operator but I think the binary operation is a bit out-of-scope for this. Could you remove the binary operation, and then move the mod over a space so it's in-line with the other 4 basic operations?

**Comment by mochidaz** [comment]
> Hi, I like the mod operator but I think the binary operation is a bit out-of-scope for this. Could you remove the binary operation, and then move the mod over a space so it's in-line with the other 4 basic operations?

Hello, I think we need one more button to move the mod operator because it will give me this error:
`ValueError: Object ID cannot contain fullstops or spaces: #op- `

**Comment by joshiemoore** [comment]
Use the character 'x' in the layout string as a spacer in the space you don't want a button to be added

**Comment by mochidaz** [comment]
> Use the character 'x' in the layout string as a spacer in the space you don't want a button to be added

Alright, done

**Comment by joshiemoore** [comment]
Actually, what I meant was "C<x%"

**Comment by mochidaz** [comment]
ah, alright then. I just thought "C<x%" looked kinda weird before. Done

**Comment by mochidaz** [comment]
Ah, https://github.com/joshiemoore/snakeware/pull/73/commits/9d406acee2ee48c36039e6495e41adedd08cf27f would make it symmetric i guess

**Pull request merged**
