### PR TITLE
Simple one-file Webbrowser with pygame.text rendering pipeline

### PR DESCRIPTION
**Pull request by deltaflyer**
Hello @joshiemoore 

here is a PR for a simple webbrowser for Snakeware that is very simplistic and uses pygame.txt-HTML-rendering for displaying websites in text-browser style.  It currently only works in the snakewm  development environments in Linux and OSX, since there is no network stack in snakeware, yet.

webbrowser

It supports retrieving webpages from HTTP(S) resources and renders HTML-source code with a minimalistic pipeline:

_html -> escaped html -> markdown -> simplified html for pygame.textbox html-rendering._

For navigating the Internet please proceed as in any other web browser:
- a valid URL, entered into to the textfield
- _ENTER_ for start browsing
- _back_ and _forward button_ of the mouse to go navigate
- _mouse click_ on links to follow the links
- _mouse-wheel_ for scrolling

 What does the browser not support:
- multithreading: while the web browser is downlaoding and rendering content, snakewm will not update
- anything that uses HTTP-verbs other than GET, e.g. POST (e.g. most forms)
- image rendering
- downloading of files other than HTTP
- Javascript
 - Websockets and other protocol stuff, (sorry no www.goole.com)
 - edge cases in rendering (its a simple hackend transforming and rendering pipeline)

I write an issue regarding the support of a network stack that is small but sufficient to run the browser
Hope that you like the contribution.

Best,
Oliver

### CODE REVIEW

**Comment by karx1** [comment]
How would navigation work for people without forward and back buttons on their mouse? From the screenshot, there seems to be no forward or back GUI buttons.

**Comment by joshiemoore** [comment]
This is great, I'll be merging it as soon as I get a chance to try it out!

**Comment by akulij** [comment]
Good idea, but the system going down, when searching something, and impossible to search on https://google.com

**Comment by joshiemoore** [comment]
I don't consider "no Google" to be a bad thing :)

**Comment by SorrowEater** [comment]
If you boot from USB, then there's no way to get internet access. Of course this can easily be fixed, assuming that under all this is a Linux distro. Arch, maybe? (Although Arch isn't an easy distro to do something like this on initially.) You can use NetworkManager, then use os to implement it into a gui (the way you can use os to clear a terminal in a regular script)

**Comment by karx1** [comment]
On Sun, Nov 1, 2020, 12:15 PM SorrowEater <notifications@github.com> wrote:

> If you boot from USB, then there's no way to get internet access.
>
No, if this were true, then you wouldn't have the ability to install any
modern linux distro via USB.

Of course this can easily be fixed, assuming that under all this is a Linux
> distro. Arch, maybe? (Although Arch isn't an easy distro to do something
> like this on initially.)
>
Snakeware uses buildroot, so it's not "based on" anything.

You can use NetworkManager,
>
Networkmanager is generally very heavy and contains a lot of stuff we don't
need. A minimal network stack based on busybox would be a better option in
this case.

then use os to implement it into a gui (the way you can use os to clear a

**Comment by SorrowEater** [comment]
Ok, @karx1, first of all, I meant you wouldn't be able to as in we had no internet access. Secondly, yeah, you're right, I'm using iwd. Why am I replying to this when I've already cleared this with you?

**Comment by SorrowEater** [comment]
@akulij, yeah, but you could specifically go to www.google.com/q=your+search+query+here and it would work. Also, It says at the very bottom of the description that protocols don't work.

**Comment by karx1** [comment]
@joshiemoore Using @SorrowEater's patch for networking, the browser now works fine on QEMU and when booting a USB.

**Pull request closed without merging**
