### PR TITLE
Create a consistent build environment

### LINKED ISSUE #29: Buildroot dependency missing
Hi,
To get the build working on Ubuntu 18-04, I had to add:
`sudo apt-get install libelf-dev`

Then it finished but with one error: `create: command not found`, but I guess just a missing comment

```
 0+0 records in
0+0 records out
0 bytes copied, 0.0003471 s, 0.0 kB/s
./build.sh: line 47: create: command not found

Welcome to fdisk (util-linux 2.34).
Changes will remain in memory only, until you decide to write them.
Be careful before using the write command.

Device does not contain a recognized partition table.
Created a new DOS disklabel with disk identifier 0x6f584148.

Command (m for help): Created a new DOS disklabel with disk identifier 0x9431d0e0.

Command (m for help): Partition type
   p   primary (0 primary, 0 extended, 4 free)
   e   extended (container for logical partitions)
Select (default p): Partition number (1-4, default 1): First sector (2048-819199, default 2048): Last sector, +/-sectors or +/-size{K,M,G,T,P} (2048-819199, default 819199): 
Created a new partition 1 of type 'Linux' and of size 399 MiB.

Command (m for help): Selected partition 1
The bootable flag on partition 1 is enabled now.

Command (m for help): The partition table has been altered.
Syncing disks.


A virtual block device has been created for snakeware.img.
Use lsblk to find the number of this device and run ./img_final.sh <num>
Example: ./img_final.sh 0 for loop0
```

### PR DESCRIPTION
**Pull request by Admicos**
This will help isolate the build from the host, and make builds more reproducible, as the user's host OS will be completely irrelevant when building.

I used Ubuntu 20.04 as the environment's base. However, any Debian-based distro should work as long as debootstrap can manage to set it up.

I managed to build a couple images with this, but it might still need to be tested a little more.

<details><summary>Old Content</summary>
<p>

This is currently a WIP, as:

1. The `build.sh` script requires root in later parts. However, I intentionally drop privileges to allow Buildroot to do its thing in a safer way. We need to find a solution to this, either by dropping privileges in `build.sh`, or extracting the parts that need root into another script, like `img_final.sh`
    - I have set up passwordless sudo in the build environment, so this might not be an issue anymore

2. I haven't tested if the build works. It's going on in the background at the moment, and I'll try to fix anything that pops up.

</p>
</details>

Also, I am not entirely sure on the `build-env-*.sh` scripts' placement. I just threw them in the snakeware directory without thinking about it, but they might be better off in a sub-directory.

Resolves #29

### CODE REVIEW

**Comment by shazz** [comment]
fails on my side:
```
I: Copying /etc/resolv.conf from host.
I: Entering chroot.
su: warning: cannot change directory to /nonexistent: No such file or directory
```

**Comment by Admicos** [comment]
On Sun May 31, 2020 at 12:07 PM +03, shazz wrote:
> su: warning: cannot change directory to /nonexistent: No such file or
> directory

That's expected. You are currently in the build environment.

I guess I should edit the shell prompt to reflect the change.

If you run `exit`, the chroot will close and you'll get back to your
original environment.

**Comment by shazz** [comment]
ok, I was not thinking it was expected :). So yes I exited the chroot then:
```
logout
I: Unmounting filesystems from chroot.
I: Cleaning leftover host files.
~/projects/pythonOS/branch/snakeware/snakeware$ ./build.sh x86-64
fatal: could not create work tree dir 'buildroot': File exists
cp: cannot create regular file '/home/shazz/projects/pythonOS/branch/snakeware/snakeware/buildroot/.config': No such file or directory
cp: cannot create regular file '/home/shazz/projects/pythonOS/branch/snakeware/snakeware/buildroot/configs/snakeware-kernel': No such file or directory
cp: cannot create directory '/home/shazz/projects/pythonOS/branch/snakeware/snakeware/buildroot/': File exists
./build.sh: line 35: cd: buildroot: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
Failed to generate rootfs.tar, not creating bootable image.
```

**Comment by Admicos** [comment]
On Sun May 31, 2020 at 12:19 PM +03, shazz wrote:
> ok, I was not thinking it was expected :). So yes I exited the chroot
> then:

You need to run the build inside the chroot.

**Comment by shazz** [comment]
yes I figured out after :) but see my edited comment, git looks unhappy...

**Comment by Admicos** [comment]
On Sun May 31, 2020 at 12:22 PM +03, shazz wrote:
> git looks unhappy...

> fatal: unable to access 'https://github.com/buildroot/buildroot.git/':
> server certificate verification failed. CAfile: none CRLfile: none

Hm, I don't think ca-certificates got installed on your setup. Can you
run `apt install ca-certificates` in the chroot? If that fixes it, I'll
add it to the additonal packages list.

I would assume it would come with the default installation, guess not.

Also, the clock might be incorrect as well, as noted here[1]. Is the
`date` command in the chroot correct?

[1]: https://stackoverflow.com/a/35824116

**Comment by shazz** [comment]
I tried `export GIT_SSL_NO_VERIFY=1` but it looks the env is corrupted now as buildroot folder was created so impossible to clone anymore.

How can I recreate it ?

`date` works except the time is in UTC instead of my timezone.

**Comment by Admicos** [comment]
On Sun May 31, 2020 at 12:31 PM +03, shazz wrote:
> I tried `export GIT_SSL_NO_VERIFY=1` but it looks the env is corrupted
> now as buildroot folder was created so impossible to clone anymore.
>
> How can I recreate it ?

In the snakeware directory, run:

  $ sudo rm -rfv work/build/buildroot/ buildroot

> `date` works except the time is in UTC instead of my timezone.

A couple hours drift, like a different timezone, shouldn't matter.

**Comment by Admicos** [comment]
>  apt fails as I'm nobody

I implemented passwordless sudo now, pull and try again if you want.

(You might need --force on pull)

**Comment by Admicos** [comment]
The build (on my system) now comes up to:
> >>>   Executing post-build script ../post-build.sh

and fails, probably because of post-build.sh path being relative to buildroot, and I do some symlink trickery to get user permissions working properly.

@joshiemoore how should I handle this?

**Comment by shazz** [comment]
> > apt fails as I'm nobody
> 
> I implemented passwordless sudo now, pull and try again if you want.
> 
> (You might need --force on pull)

works! Currently running build.sh

**Comment by Admicos** [comment]
> probably because of post-build.sh path being relative to buildroot, and I do some symlink trickery to get user permissions working properly.
> 
> @joshiemoore how should I handle this?

Nevermind. I now create a new user instead of hijacking the nobody user, which should fix this, along with allowing better integration with the host, as you no longer have weird permissions on buildroot and any generated files.

I'll be pushing this if my test works.

**Comment by Admicos** [comment]
@joshiemoore is there another way of creating the disk image? I am getting errors from `kpartx` because I haven't enabled device-mapper in my host kernel.

```
/dev/mapper/control: open failed: No such device
Failure to communicate with kernel device-mapper driver.
Check that device-mapper is available in the kernel.
Incompatible libdevmapper 1.02.167 (2019-11-30) and kernel driver (unknown version).
device mapper prerequisites not met
```

**Comment by shazz** [comment]
ok obviously, I ended with the same issue:
```
>>>   Executing post-build script ../post-build.sh
/bin/bash: ../post-build.sh: No such file or directory
make: *** [Makefile:773: target-finalize] Error 127
Failed to generate rootfs.tar, not creating bootable image.
```

**Comment by Admicos** [comment]
> ok obviously, I ended with the same issue

Try pulling now, I tried fixing it.

I added a lot of new packages & fiddled with some scripts as well, so you might want to just re-create the work directory (don't forget to remove the buildroot symlink)

I am currently re-installing my chroot to make sure it works when someone tries it from scratch, so I probably won't work on this for a while (overnight at the worst case)

**Comment by shazz** [comment]
Ok, restarting from scratch. Pretty long :)

**Comment by karx1** [comment]
So if I'm understanding correctly, it needs a Debian-based host? Or does it set it up completely separately?

**Comment by Admicos** [comment]
On Sun May 31, 2020 at 5:04 PM +03, Yash Karandikar wrote:
> So if I'm understanding correctly, it needs a Debian-based host? Or does
> it set it up completely separately?

Nope. It downloads debootstrap and creates a Debian-based environment
seperate from the host OS.

As long as your host runs x86 and has the build-env.sh's dependencies
(see the first lines of the script), you should be good to go.

I am developing it under KISS Linux, which isn't based on Debian, for
example.

**Comment by shazz** [comment]
ok, 2 issues with your latest commit: 

pygame did not built to to host includes
```
    building 'pygame.imageext' extension
    creating build/temp.linux-x86_64-3.8
    creating build/temp.linux-x86_64-3.8/src_c
    /snakeware/snakeware/buildroot/output/host/bin/x86_64-snakeware-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -Os -fPIC -D_REENTRANT -DENABLE_NEWBUF=1 -I/usr/X11R6/include -I/usr/include/SDL -I/usr/include/SDL -I/usr/include -I/usr/include -I/snakeware/snakeware/buildroot/output/target/usr/include/python3.8 -c src_c/imageext.c -o build/temp.linux-x86_64-3.8/src_c/imageext.o
    x86_64-snakeware-linux-gnu-gcc: ERROR: unsafe header/library path used in cross-compilation: '-I/usr/include/SDL'
    ---
    For help with compilation see:
        https://www.pygame.org/wiki/Compilation
    To contribute to pygame development see:
        https://www.pygame.org/contribute.html
    ---
    error: command '/snakeware/snakeware/buildroot/output/host/bin/x86_64-snakeware-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /snakeware/snakeware/buildroot/../buildroot/output/target/usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-pa35sw85/pygame/setup.py'"'"'; __file__='"'"'/tmp/pip-install-pa35sw85/pygame/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-vjgbvut0/install-record.txt --single-version-externally-managed --compile --install-headers /snakeware/snakeware/buildroot/output/target/usr/include/python3.8/pygame Check the logs for full command output.
touch /snakeware/snakeware/buildroot/output/target/usr

```

then: `grub-install: not found`

````
~/snakeware $ sudo ./img_final.sh 26
mke2fs 1.45.5 (07-Jan-2020)
Discarding device blocks: done                            
Creating filesystem with 102144 4k blocks and 102144 inodes
Filesystem UUID: 3e3ca1d5-9e81-4d72-acae-830288f462a6
Superblock backups stored on blocks: 
	32768, 98304

Allocating group tables: done                            
Writing inode tables: done                            
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: done

./img_final.sh: 29: grub-install: not found
loop deleted : /dev/loop26
````

**Comment by Admicos** [comment]
On Sun May 31, 2020 at 5:28 PM +03, shazz wrote:
> ok, 2 issues with your latest commit:
>
> pygame did not built to to host includes
> [...]
> x86_64-snakeware-linux-gnu-gcc: ERROR: unsafe header/library path used
> in cross-compilation: '-I/usr/include/SDL'

The way pygame is installed via the post-build script might be the issue
here. I'll see what I can do tomorrow, as it's getting kinda late here.

> ./img_final.sh: 29: grub-install: not found

Oh, I didn't install grub into the build chroot. Try apt install'ing
`grub2-common`. I'll add it into the default set if it works.

**Comment by shazz** [comment]
not enough :)

```
/snakeware $ sudo ./img_final.sh 26
mke2fs 1.45.5 (07-Jan-2020)
Discarding device blocks: done                            
Creating filesystem with 102144 4k blocks and 102144 inodes
Filesystem UUID: 82e4ed9e-c0f7-49ab-a4c9-9c576f810fe4
Superblock backups stored on blocks: 
	32768, 98304

Allocating group tables: done                            
Writing inode tables: done                            
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: done

grub-install: error: /usr/lib/grub/i386-pc/modinfo.sh doesn't exist. Please specify --target or --directory.
loop deleted : /dev/loop26
```

**Comment by Admicos** [comment]
On Sun May 31, 2020 at 5:40 PM +03, shazz wrote:
> not enough :)
> [....]
> grub-install: error: /usr/lib/grub/i386-pc/modinfo.sh doesn't exist.
> Please specify --target or --directory.

Try `grub2` then. I don't really know how Ubuntu's packages work, so
I've been using packages.ubuntu.com's search.

**Comment by shazz** [comment]
whoooho, apt install grub2 proposes me to install grub2 on my real drive... I guess that's a bad idea

````
The grub-pc package is being upgraded. This menu allows you to select which devices you'd like grub-install to be automatically run for, if any.

Running grub-install automatically is recommended in most situations, to prevent the installed GRUB core image from getting out of sync with GRUB modules or grub.cfg.

If you're unsure which drive is designated as boot drive by your BIOS, it is often a good idea to install GRUB to all of them.

Note: it is possible to install GRUB to partition boot records as well, and some appropriate partitions are offered here. However, this forces GRUB to use the blocklist mechanism, which makes
it less reliable, and therefore is not recommended.

  1. /dev/sda (500107 MB; ???)  2. /dev/dm-0 (495624 MB; ubuntu--vg-root)

(Enter the items you want to select, separated by spaces.)

GRUB install devices: 

````

**Comment by Admicos** [comment]
On Sun May 31, 2020 at 5:48 PM +03, shazz wrote:
> whoooho, apt install grub2 proposes me to install grub2 on my real
> drive... I guess that's a bad idea

Ouch. I got that too just now.

Try installing just `grub-pc` and `grub2-common` as mentioned at [1].

You might want to remove `grub2`, and autoremove before trying that to
get rid of any half-finished installations.

[1]: https://askubuntu.com/a/1107229

**Comment by shazz** [comment]
grub-pc triggers this configuration:

````
Configuring grub-pc
-------------------

The grub-pc package is being upgraded. This menu allows you to select which devices you'd like grub-install to be automatically run for, if any.

Running grub-install automatically is recommended in most situations, to prevent the installed GRUB core image from getting out of sync with GRUB modules or grub.cfg.

If you're unsure which drive is designated as boot drive by your BIOS, it is often a good idea to install GRUB to all of them.

Note: it is possible to install GRUB to partition boot records as well, and some appropriate partitions are offered here. However, this forces GRUB to use the blocklist mechanism, which makes
it less reliable, and therefore is not recommended.

  1. /dev/sda (500107 MB; ???)  2. /dev/dm-0 (495624 MB; ubuntu--vg-root)

(Enter the items you want to select, separated by spaces.)

GRUB install devices: 
````

**Comment by Admicos** [comment]
On Sun May 31, 2020 at 5:53 PM +03, shazz wrote:
> grub-pc triggers this configuration:

I am lost then. I am not really experienced with apt, so I don't know if
there is a good way of bypassing this prompt.

**Comment by shazz** [comment]
ok so I just cancelled the configuration, packages were installed. So I ran the last command and:

````
Installing for i386-pc platform.
Installation finished. No error reported.
loop deleted : /dev/loop26
````

Let me try the image now

**Comment by karx1** [comment]
> Which devices you'd like to install grub to, if any

This might be stupid, but could you just press enter without specifying any drives?

**Comment by karx1** [comment]
oh, nevermind, didn't read the latest comments

**Comment by karx1** [comment]
Also, why is it trying to install for i386-pc? Isn't only x86-64 supported?

**Comment by shazz** [comment]
@karx1 : I don't trust default values :)

@Admicos: the image works. Except pygame is not there as expected. Good job!

**Comment by karx1** [comment]
What do you mean pygame is not there as expected?

**Comment by Admicos** [comment]
On Sun May 31, 2020 at 5:58 PM +03, shazz wrote:
> @Admicos: the image works. Except pygame is not there as expected. Good
> job!

Nice!

Once we can get pygame working, and find a way around installing Grub
without a prompt (maybe debootstrap will skip the prompt? someone should
try that) I assume this will be ready to be merged.

(Not requiring device-mapper would be good too, but only some exotic
configurations, like mine don't include it, so that might be fine)

(For pygame, it could be better to just create a buildroot package for
it, instead of downloading it post-install via pip, but I imagine that
would be outside the scope of this PR, so we should fix what we have,
and think about that later.)

I also noticed that both of us more or less stumbled on the exact same
errors at more or less the same time, which gives me confidence that the
PR does what I expected it to do.

**Comment by shazz** [comment]
> What do you mean pygame is not there as expected?

see https://github.com/joshiemoore/snakeware/pull/30#issuecomment-636532625

**Comment by shazz** [comment]
@Admicos

Maybe asking apt to install `grub-common` and `grub-pc-bin` without configuring:
https://serverfault.com/questions/227190/how-do-i-ask-apt-get-to-skip-any-interactive-post-install-configuration-steps

Some tests to do...

I'll take a look at how to specify the pygame compilation flags.

**Comment by shazz** [comment]
About pygame, maybe it would be safer to recompile from source into the chroot ?

This is what I use to compile on my laptop the latest version (2.0.0.dev9):

```
sudo apt-get update
sudo apt install libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libfreetype6-dev python3-setuptools python3-dev python3 libportmidi-dev
sudo apt-get build-dep libsdl2 libsdl2-image libsdl2-mixer libsdl2-ttf libfreetype6 python3 libportmidi0
git clone https://github.com/pygame/pygame.git
cd pygame
python3 setup.py -config -auto -sdl2
python3 setup.py install --user
```

**Comment by Admicos** [comment]
On Sun May 31, 2020 at 6:18 PM +03, shazz wrote:
> About pygame, maybe it would be safer to recompile from source into the
> chroot ?

Pygame is currently built via the post-build.sh script that gets ran
from Buildroot, and Buildroot seems to have a special option[1] to disallow
any libraries that might "leak" into the build environment. So the error
is happening because we're recompiling from source inside the chroot.
The fix for this would be to either try disabling said option from the
Buildroot config, or fix whatever Pygame is doing to make the build less
dependent on the host, even if the host is in our control (like in our
case).

[1]: https://stackoverflow.com/a/44052528

**Comment by shazz** [comment]
look like the post-build.sh only call `pip install` so the wheel will decide how to build it. 
That's why I like to try from the sources, maybe more freedom?

**Comment by Admicos** [comment]
On Sun May 31, 2020 at 6:27 PM +03, shazz wrote:
> look like the post-build.sh only call `pip install` so the wheel will
> decide how to build it.
> That's why I like to try from the sources, maybe more freedom?

At the end, I would assume it would be the same compiler with the same
arguments that would be compiling the sources, as IIRC pip does 
essentially the same thing as doing it manually, but you can try if you
want.

I'll look into the Pygame thing tomorrow, so feel free to just mess
around and maybe you'll find a better solution than what I'd come up 
with.

**Comment by shazz** [comment]
Yes I think you're right... Should be the same except if I modify the sources :)

https://github.com/pygame/pygame/search?q=-I%2Fusr%2Finclude%2FSDL&unscoped_q=-I%2Fusr%2Finclude%2FSDL

**Comment by shazz** [comment]
So... mixed results:

 - Calling `sudo apt-get install grub2-common grub-pc-bin` looks to be ok  

 - Compiling pygame into the chroot works, no problem

````
sudo apt install libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libfreetype6-dev python3-setuptools python3-dev python3 libportmidi-dev
sudo apt-get build-dep libsdl2 libsdl2-image libsdl2-mixer libsdl2-ttf libfreetype6 python3 libportmidi0
git clone https://github.com/pygame/pygame.git
cd pygame
python3 setup.py -config -auto -sdl2
````

 - I installed pygame for the user and for all users

```` 
python3 setup.py install --user
sudo python3 setup.py install
````

 - I built the image, ran it... but import pygame failed from the interpreter

So I guess I forgot something...

**Comment by karx1** [comment]
> import pygame failed

Did it raise an ImportError or something else?

**Comment by Admicos** [comment]
Oh hey, Buildroot seems to already have a package for Pygame (`BR2_PACKAGE_PYTHON_PYGAME`).

**Comment by Admicos** [comment]
SnakeWM

SnakeWM works now, Installing Grub in the chroot is the only thing left :)

**Comment by Admicos** [comment]
This should be more or less done now :)

**Comment by Admicos** [comment]
Rebased the PR to fix the merge conflicts.

While it should be ready to be merged, I would advise testing before merging, just to make sure there aren't any issues I haven't caught in the process of rebasing.

**Comment by shazz** [comment]
Good job! Better like that.
I'll try it during the day.
A few questions/comments:
 - Maybe have a dedicated script to delete the loop, especially during debug time. Or at least each time I tried an image, the loop was deleted by img_final.sh and I had to recreate everything.
 - How can I delete all the remaining loops/mount from my buggy experiments ?
- Would it be possible to define some part of the image as read-only to mimic the ROM aspect of the C64? like that no corruption possible ?
- from the interpreter, os.listdir() shows everything from root, shouldn't it be a userspace ?

Except that, I'll probalby bother you a little to understand how to customize this build, I have some ideas :)

**Comment by Admicos** [comment]
On Mon Jun 1, 2020 at 8:30 AM +03, shazz wrote:
> A few questions/comments:
> - Maybe have a dedicated script to delete the loop, especially during
> debug time. Or at least each time I tried an image, the loop was deleted
> by img_final.sh and I had to recreate everything.

> - How can I delete all the remaining loops/mount from my buggy
> experiments ?

The loop parts are from the original build scripts, I haven't touched
them myself. You might want to ask @joshiemoore for that.

> - Would it be possible to define some part of the image as read-only to
> mimic the ROM aspect of the C64? like that no corruption possible ?

It is possible, yes.

> - from the interpreter, os.listdir() shows everything from root,
> shouldn't it be a userspace ?

Again, that's for joshiemoore to decide.

> Except that, I'll probalby bother you a little to understand how to
> customize this build, I have some ideas :)

If you've done a build already, cd into buildroot and run `make
menuconfig`. After doing your changes, copy the `.config` file it
creates into `config/x86-64-buildroot-config` and run build.sh

**Comment by shazz** [comment]
ok I'll try to see if I can add the Buildroot openGL and vulkan packages to get 3D support in pygame

**Comment by karx1** [comment]
Looks like the chroot doesn't work on my system, due to the "addgroup" command not being found.
There is also no arch linux package for this.
image

**Comment by Admicos** [comment]
On Mon Jun 1, 2020 at 1:25 PM +03, Yash Karandikar wrote:
> Looks like the chroot doesn't work on my system, due to the "addgroup"
> command not being found.
> There is also no arch linux package for this.

addgroup is supposed to be in the chroot. I have no clue why it isn't
working for you. Can you try removing the work directory (you'll need
root access) and re-try?

**Comment by Admicos** [comment]
On Mon Jun 1, 2020 at 1:48 PM +03, Yash Karandikar wrote:
> Removed work directory, re-ran script, still the same as before

Can you try adding `adduser` to line 46 (--include ...) of build-env.sh
and try again with a clean work directory?

I didn't add it explicitly, but so far it always came by default.

**Comment by karx1** [comment]
I'll try it, but it looks like adduser is actually being installed by default.
image

**Comment by karx1** [comment]
Nope, it didn't work

**Comment by karx1** [comment]
OK, tried changing to groupadd instead of addgroup, but that didn't work

**Comment by joshiemoore** [comment]
Sorry that I've been silent on this for so long, it's a long conversation and big diff so I just haven't had a chance to go through it all yet. It looks like you've done a really amazing job from what I've seen so far.

Have you had a chance to test this on a few different systems yet and it works? The current build system has been working for me, so I'm just hesitant to mess with it again, hahaha. You seem to be a lot more experienced with creating these build systems than I am though.

I also don't fully understand how to add more pip modules to this, but like I said, I haven't looked at it very closely. I'm excited to check it out, thank you so much for your contributions!

**Comment by Admicos** [comment]
On Tue Jun 2, 2020 at 6:51 PM +03, Josh Moore wrote:
> Sorry that I've been silent on this for so long, it's a long
> conversation and big diff so I just haven't had a chance to go through
> it all yet. It looks like you've done a really amazing job from what
> I've seen so far.
>
> Have you had a chance to test this on a few different systems yet and it
> works? The current build system has been working for me, so I'm just
> hesitant to mess with it again, hahaha. You seem to be a lot more
> experienced with creating these build systems than I am though.

I currently haven't tested anywhere other than my own setup, but
tomorrow I might try on my second computer as well.

Aside from that, A couple other people also tested it as you can see
from the comment history.

Also, I am not that experienced with build stuff specifically. It was
more like "I couldn't get it to build, so I decided to find a way around
it."

That's why there are still some TODOs left over, and things probably can
be a lot better than what I crafted in about a day.

> I also don't fully understand how to add more pip modules to this, but
> like I said, I haven't looked at it very closely. I'm excited to check
> it out, thank you so much for your contributions!

For pip modules, see Buildroot documentation[1], particularly "17.8.3.
Generating a python-package from a PyPI repository", which worked on
pygame-gui but not on pytts3x in my experience.

[1]: https://buildroot.org/downloads/manual/manual.html#_infrastructure_for_python_packages

Aside from that, thanks! I have more plans about the internal parts of
the system, though not entirely sure how many are feasible.

**Comment by shazz** [comment]
On my side I tested the latest commit successfully on Ubuntu 18.04 (build tested and working)

**Comment by Admicos** [comment]
Also, a quick little note (mostly to myself before going to bed):

BR2_EXTERNAL might be a better way of managing buildroot confiiguration then the current file copying ways: https://buildroot.org/downloads/manual/manual.html#outside-br-custom

**Comment by Admicos** [comment]
I have marked this pr as a draft until I can get both BR2_EXTERNAL working (done, testing in the background) and pytts3x (and suplemon too now, i think) packaged, and tested in my second computer.

**Comment by Admicos** [comment]
I found why the adduser issue happens (and why it only sometimes happens)

The chroot inherits the host's $PATH, which, if doesn't include (/usr)/sbin, causes the chroot to fail finding the adduser binary.

cc @karx1

**Comment by Admicos** [comment]
just dumping some random documentation here. these should be written in a proper build customization documentation page if possible later on:

Please run build.sh at least once before trying these
All commands assume chroot
All (initial) `cd` commands expect you to be in the snakeware directory containing build.sh

If something's not here, check `make help` and [the Buildroot manual](https://buildroot.org/downloads/manual/manual.html)

## Editing Buildroot configuration

```sh
cd buildroot
make menuconfig
make savedefconfig DEFCONFIG=../external/configs/x86-64_defconfig
```

### Loading Buildroot configuration if you haven't run build.sh

```sh
cd buildroot
make x86-64_defconfig
```

## Editing Kernel configuration

```sh
cd buildroot
make linux-menuconfig
make linux-update-defconfig
```

## Adding new files into the filesystem

```sh
cd external/overlay
# copy your files here
```

## Adding new Python packages

### If scanpypi works

```sh
cd buildroot
python3 utils/scanpypi <packagename> -o ../external/
```

### If it doesn't

```sh
cd external
edit Config.in

# append the following line, without the hash:
# source "$BR2_EXTERNAL_SNAKEWARE_PATH/package/python-<packagename>/Config.in"

cd package
cp -r python-pyttsx3 python-<packagename>
cd python-<packagename>

edit Config.in
# change package names, add a description, etc.
# check pygame-gui Config.in for how to add dependencies

mv python-pyttsx3.mk python-<packagename>.mk
mv python-pyttsx3.hash python-<packagename>.hash

edit python-<packagename>.*

# edit the .mk file to include all neccesary information
# edit the .hash file to the hash of the downloaded file
```

**Comment by Admicos** [comment]
Alright, just tested this PR on my second computer, it built fine and the img file is only 4 bytes shorter, so I'm just going to assume it'll work fine as well.

**Comment by Admicos** [comment]
Tried rebasing this branch again, but the Buildroot config might be messed up, please test!

**Comment by karx1** [comment]
@Admicos now "cat" is not found :/

**Comment by Admicos** [comment]
On Fri Jun 5, 2020 at 3:14 PM +03, Yash Karandikar wrote:
> @Admicos now "cat" is not found :/

Can you delete the work directory (will need root), re-run the
build-env.sh file, and upload all the output somewhere?

**Comment by joshiemoore** [comment]
Hi, after a lot of thought and testing, I don't think I'm going to go with the new chroot build system. I understand the motivation behind this change, but it seems to be a layer of additional complexity that I'm not sure is necessary. I've found that buildroot seems to isolate itself fairly well. Also, I tried several times to get this to build on my system and was not able to successfully build. I kept getting errors about not being able to install various packages (1 or 2 each time, different every time) and it would not enter the chroot.

Copying some configs into a local clone of buildroot and typing `make` is very cross-platform, reproducible behavior, and this is basically all `build.sh` currently does. If this doesn't work on someone's machine, that is a problem with their machine, not with the build system. These people should reference the buildroot documentation and configure their local system to its specifications. Ultimately, it's most important to me that full builds work on my machines, and this is the case for the current build system.

I say this recognizing and appreciating the amount of work you've been putting into this, I feel like a jerk because your contributions have been invaluable so far. I really want to incorporate some of the other ideas you've developed on this branch, such as adding configs to build pip packages within buildroot instead of calling the compiled python3 binary in `post-build.sh`.

Thank you for all your help so far, I'm open to further discussion and input, but I've pretty much made my mind up on this by now. I'm really excited that such bright people as yourself are interested in contributing to this project, we are on our way to something awesome

**Comment by Admicos** [comment]
On Fri Jun 5, 2020 at 6:48 PM +03, Josh Moore wrote:
> Copying some configs into a local clone of buildroot and typing `make`
> is very cross-platform, reproducible behavior, and this is basically all
> `build.sh` currently does. If this doesn't work on someone's machine,
> that is a problem with their machine, not with the build system. These
> people should reference the buildroot documentation and configure their
> local system to its specifications. 

Fair enough. I started this because my current system runs on a very
exotic configuration, with stuff like Busybox instead of GNU Corelibs,
but since most other systems use the latter by default, I do see your
point on adding extra complexity for not much gain.

> I really want to incorporate some of the other  ideas you've developed 
> on this branch, such as adding configs to build pip packages within 
> buildroot instead of calling the compiled python3 binary in 
> `post-build.sh`.

I can create a new PR if you want, that will contain just the BR2_EXTERNAL
folder integration (for keeping configuration seperate from buildroot
sources, without needing a special build script to copy it all) and the
Python packages.

> Thank you for all your help so far, I'm open to further discussion and
> input, but I've pretty much made my mind up on this by now. I'm really
> excited that such bright people as yourself are interested in
> contributing to this project, we are on our way to something awesome

Any time :)

ps: Feel free to look at the `external` branch in my repo if you're
looking for further stuff to merge in.

**Pull request closed without merging**
