### PR TITLE
Add "snakewm" command to the shell

### PR DESCRIPTION
**Pull request by GarbageHamburger**
This PR adds a `win` statement to the Python shell started by Snakeware, which will start-up SnakeWM when evaluated.

```
>>> win
# SnakeWM launches
```

### CODE REVIEW

**Comment by GarbageHamburger** [comment]
To be honest the entire PR was meant as a joke and a jab at Windows, but if it's actually useful you're welcome to use the idea ;)

**Comment by callmepavo** [comment]
using this could recreate some basic bash commands (cd, ls) as python functions to move current working directory more easily than `import os;os.chdir()` and having to write a for loop to print out the file & folders in current working directory

**Comment by GarbageHamburger** [comment]
I will change the command to `snakewm`, and open a separate PR for other basic utilities once this is merged.

**Comment by Admicos** [comment]
On Tue Jun 2, 2020 at 1:43 PM +03, callmepavo wrote:
> using this could recreate some basic bash commands (cd, ls) as python
> functions to move current working directory more easily than `import
> os;os.chdir()` and having to write a for loop to print out the file &
> folders in current working directory

I don't think Python has any other "magic keywords", so why add more? If
someone starts learning Python because snakeware, would it really be 
useful to teach commands that won't apply to the rest of the language?

I mean, having some packages pre-imported, and creating functions like
ls(<optional=dir>), cd(<optional=dir>) would be fine, but having "magic
keywords" would make the system feel inconsistent (in my opinion,
anyway).

To be clear, I am not completely opposed to the idea. I just want to
bring attention to consistency with the rest of the Python language.

**Comment by callmepavo** [comment]
> On Tue Jun 2, 2020 at 1:43 PM +03, callmepavo wrote: using this could recreate some basic bash commands (cd, ls) as python functions to move current working directory more easily than `import os;os.chdir()` and having to write a for loop to print out the file & folders in current working directory
> I don't think Python has any other "magic keywords", so why add more? If someone starts learning Python because snakeware, would it really be useful to teach commands that won't apply to the rest of the language? I mean, having some packages pre-imported, and creating functions like ls(<optional=dir>), cd(<optional=dir>) would be fine, but having "magic keywords" would make the system feel inconsistent (in my opinion, anyway). To be clear, I am not completely opposed to the idea. I just want to bring attention to consistency with the rest of the Python language.

Yeah true, it could undermine the idea of the project a bit to ape things from normal OSs that are unpythonic.

**Comment by GarbageHamburger** [comment]
I also added some early abstraction for command definitions.

@Admicos I think the convenience and practicality of keeping these as "magic keywords" beats out possible confusion. Maybe information can be added to the Python shell header to identify the shell as "the Snakeware shell", which could help.

**Comment by callmepavo** [comment]
"Python 3.8.2 Shell + snakeware 0.0.2 Shell"?

**Comment by callmepavo** [comment]
It seems cleaner to me to just have them as functions that are pre-imports, like an extension of regular __builtin__ rather than introducing new keywords all together.

**Comment by joshiemoore** [comment]
My preference is that we not try to recreate bash, I think it would be great if coding in Python were a regular part of the user experience. I think the built in commands should be limited to convenience functions for loading things like snakewm, snake_games, etc, without having to manually import them and run them

**Comment by callmepavo** [comment]
> My preference is that we not try to recreate bash, I think it would be great if coding in Python were a regular part of the user experience. I think the built in commands should be limited to convenience functions for loading things like snakewm, snake_games, etc, without having to manually import them and run them

That's more than fair enough, this seems like a very "pure" python experience.  It could be apart of the experience that if you want to recreate bash like functions or additional commands, you can add them them to startup.py yourself.

**Comment by GarbageHamburger** [comment]
My suggestion, then, is to add something like this snippet:

```python
import os

# Load the RC file
home_dir = os.getenv("HOME")
rc_file = os.path.join(home_dir, ".snakerc.py")
if os.isfile(rc_file):
    with open(rc_file) as f:
        rc = compile(f.read(), rc_file, "exec")
        exec(rc)
```

This, of course, expects shell variables like `HOME` and `USER` being set. If they aren't, then groundwork would need to be done on that first. In general, something like `/etc/profile` needs to be set up for Snakeware's shell.

**Pull request merged**
