### PR TITLE
Userspace build

### PR DESCRIPTION
**Pull request by alexandruavadanii**
- use FUSE to avoid root level access during build (and avoid kpartx/loop devices etc.);
- cleanup some warnings reported by running `shellcheck build.sh` (most if not all are double quoting warnings);
- populate target image's `/etc/os-release` with snakeware specific values;

### CODE REVIEW

**Comment by Admicos** [comment]
> - use FUSE to avoid root level access during build (and avoid
> kpartx/loop devices etc.);

I would be rather favor of letting Buildroot generate a hybrid ISO
instead of doing it manually via FUSE & co.

Once I get my development environment working on my new system install,
I'll try to port my iso generation config from my previous experiments
branch. (Up ony my fork if you want to take a look at it)

Letting Buildroot do it's thing allows us to:

(a) Not care about image size, as Buildroot can determine it on its
own, and in my previous experiments, can shrink it down to ~60-70 MBs
via transparent compression & tricks like that.

(b) Clean up build.sh into just "clone bulidroot" and "make" (assuming
Josh merges my BR2_EXTERNAL config from PR 30 (or I might abandon it
and create a new one per Josh's responses))

Also, anything FUSE doesn't work under a nix-shell, but that's probably
not relevant to most people who will build Snakeware.

**Comment by alexandruavadanii** [comment]
To be honest,  I mostly wanted to get rid of the manual build step with kpartx/loop devices - I have some previous bad experiences with them and always wanted to try out FUSE.
I like the buildroot ISO idea, although I'm not sure it works for embedded systems with custom firmwares like Raspberry Pi.

As for cleaning up build.sh, that sounds awesome, I did some experiments of my own (creating an UEFI image for x86_64 with GPT + 2 partitions) and the complexity of build.sh gets really, really annoying computing offsets and hacking partition and disk images with FUSE ...

So I'm definitely in favor of letting buildroot handle the image creation and I hope we can find a solution for systems that don't support cdrom images (if any).

PS: Never used NIX, so I didn't know about that limitation.

**Comment by Admicos** [comment]
> although I'm not sure it works for embedded systems with custom
> firmwares like Raspberry Pi.

I am not sure about that, yeah. But at least for x86, we can let
Buildroot do the heavy lifting.

> I hope we can find a solution for systems that don't support cdrom
> images (if any).

I guess we could make post build scripts (outside Buildroot, the
post-build.sh inside Buildroot won't work for that) for different
platforms that will package the rootfs in a different way for each.
 
> PS: Never used NIX, so I didn't know about that limitation.

It's actually more about fusermount having the SUID bit set that causes
the issue, because Nix doesn't use the general classing file system
hierarchy, and the compatibility layer for programs that are unaware of
it use user namespaces, which SUID bits don't work under without
tweaking that Nix developers haven't done (I assume)

**Comment by joshiemoore** [comment]
It would be great to have Buildroot handle the IMG/ISO/<whatever we end up going with> generation itself, without having to manually generate it in `build.sh`. It seems to me that ISO should be preferred, as one of the most common questions people have is "how do I convert IMG to ISO?" so maybe we would do well to just release ISOs.

I've been working on the Raspberry Pi buildroot config, and the buildroot process for RPi spits out an `sdcard.img` image file to get flashed to the SD card at its conclusion, no further action required. I love this and I think it would be great to have the x86-64 build behave similarly.

In terms of this actual PR, it looks great for our current build process and I'll merge it soon. Thank you guys for all of your amazing contributions so far.

**Comment by joshiemoore** [comment]
See #98

**Pull request closed without merging**
