### PR TITLE
Improve layout of calculator buttons

### PR DESCRIPTION
**Pull request by GarbageHamburger**
The old layout looks atrocious. This layout emulates traditional desktop calculators.

### CODE REVIEW

**Comment by callmepavo** [comment]
This is good, the old layout looked like there was a bug.

**Comment by callmepavo** [comment]
Could also replace the screenshot.png with new calculator

**Comment by GarbageHamburger** [comment]
I can't run Snakeware on my machine ATM, I'll update the screenshot once I can.

**Comment by joshiemoore** [comment]
n-no u

**Pull request merged**
